/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/airplane/model.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function Airplane(props) {
  const { nodes, materials } = useGLTF('./models/airplane/model.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <PerspectiveCamera makeDefault={false} far={100000} near={70} fov={45} position={[974.259, 558.907, 304.445]} rotation={[-1.02, -0.95, -0.924]} />
        <group position={[0, 47.955, -4.446]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.704}>
          <group position={[-181.468, -51.186, -45.114]} rotation={[-2.967, 0, 0]}>
            <mesh geometry={nodes.mesh_1_instance_1.geometry} material={nodes.mesh_1_instance_1.material} />
            <mesh geometry={nodes.mesh_1_instance_2.geometry} material={nodes.mesh_1_instance_2.material} position={[21.3, 0, 0]} />
            <mesh geometry={nodes.mesh_1_instance_3.geometry} material={nodes.mesh_1_instance_3.material} position={[42.6, 0, 0]} />
            <mesh geometry={nodes.mesh_1_instance_4.geometry} material={nodes.mesh_1_instance_4.material} position={[63.9, 0, 0]} />
            <mesh geometry={nodes.mesh_1_instance_5.geometry} material={nodes.mesh_1_instance_5.material} position={[85.2, 0, 0]} />
            <mesh geometry={nodes.mesh_1_instance_6.geometry} material={nodes.mesh_1_instance_6.material} position={[106.5, 0, 0]} />
            <mesh geometry={nodes.mesh_1_instance_7.geometry} material={nodes.mesh_1_instance_7.material} position={[127.8, 0, 0]} />
            <mesh geometry={nodes.mesh_1_instance_8.geometry} material={nodes.mesh_1_instance_8.material} position={[149.1, 0, 0]} />
            <mesh geometry={nodes.mesh_1_instance_9.geometry} material={nodes.mesh_1_instance_9.material} position={[170.4, 0, 0]} />
            <mesh geometry={nodes.mesh_1_instance_10.geometry} material={nodes.mesh_1_instance_10.material} position={[191.7, 0, 0]} />
            <mesh geometry={nodes.mesh_1_instance_11.geometry} material={nodes.mesh_1_instance_11.material} position={[213, 0, 0]} />
            <mesh geometry={nodes.mesh_1_instance_12.geometry} material={nodes.mesh_1_instance_12.material} position={[234.3, 0, 0]} />
            <mesh geometry={nodes.mesh_1_instance_13.geometry} material={nodes.mesh_1_instance_13.material} position={[255.6, 0, 0]} />
            <mesh geometry={nodes.mesh_1_instance_14.geometry} material={nodes.mesh_1_instance_14.material} position={[276.9, 0, 0]} />
            <mesh geometry={nodes.mesh_1_instance_15.geometry} material={nodes.mesh_1_instance_15.material} position={[298.2, 0, 0]} />
            <mesh geometry={nodes.mesh_1_instance_16.geometry} material={nodes.mesh_1_instance_16.material} position={[319.5, 0, 0]} />
            <mesh geometry={nodes.mesh_1_instance_17.geometry} material={nodes.mesh_1_instance_17.material} position={[340.8, 0, 0]} />
            <mesh geometry={nodes.mesh_1_instance_18.geometry} material={nodes.mesh_1_instance_18.material} position={[362.1, 0, 0]} />
            <mesh geometry={nodes.mesh_1_instance_19.geometry} material={nodes.mesh_1_instance_19.material} position={[383.4, 0, 0]} />
            <mesh geometry={nodes.mesh_1_instance_20.geometry} material={nodes.mesh_1_instance_20.material} position={[404.7, 0, 0]} />
            <mesh geometry={nodes.mesh_1_instance_21.geometry} material={nodes.mesh_1_instance_21.material} position={[426, 0, 0]} />
            <mesh geometry={nodes.mesh_1_instance_22.geometry} material={nodes.mesh_1_instance_22.material} position={[447.3, 0, 0]} />
            <mesh geometry={nodes.mesh_1_instance_23.geometry} material={nodes.mesh_1_instance_23.material} position={[468.6, 0, 0]} />
          </group>
          <group position={[-181.468, -51.264, 36.191]} rotation={[-0.175, 0, 0]}>
            <mesh geometry={nodes.mesh_2_instance_1.geometry} material={nodes.mesh_2_instance_1.material} />
            <mesh geometry={nodes.mesh_2_instance_2.geometry} material={nodes.mesh_2_instance_2.material} position={[21.3, 0, 0]} />
            <mesh geometry={nodes.mesh_2_instance_3.geometry} material={nodes.mesh_2_instance_3.material} position={[42.6, 0, 0]} />
            <mesh geometry={nodes.mesh_2_instance_4.geometry} material={nodes.mesh_2_instance_4.material} position={[63.9, 0, 0]} />
            <mesh geometry={nodes.mesh_2_instance_5.geometry} material={nodes.mesh_2_instance_5.material} position={[85.2, 0, 0]} />
            <mesh geometry={nodes.mesh_2_instance_6.geometry} material={nodes.mesh_2_instance_6.material} position={[106.5, 0, 0]} />
            <mesh geometry={nodes.mesh_2_instance_7.geometry} material={nodes.mesh_2_instance_7.material} position={[127.8, 0, 0]} />
            <mesh geometry={nodes.mesh_2_instance_8.geometry} material={nodes.mesh_2_instance_8.material} position={[149.1, 0, 0]} />
            <mesh geometry={nodes.mesh_2_instance_9.geometry} material={nodes.mesh_2_instance_9.material} position={[170.4, 0, 0]} />
            <mesh geometry={nodes.mesh_2_instance_10.geometry} material={nodes.mesh_2_instance_10.material} position={[191.7, 0, 0]} />
            <mesh geometry={nodes.mesh_2_instance_11.geometry} material={nodes.mesh_2_instance_11.material} position={[213, 0, 0]} />
            <mesh geometry={nodes.mesh_2_instance_12.geometry} material={nodes.mesh_2_instance_12.material} position={[234.3, 0, 0]} />
            <mesh geometry={nodes.mesh_2_instance_13.geometry} material={nodes.mesh_2_instance_13.material} position={[255.6, 0, 0]} />
            <mesh geometry={nodes.mesh_2_instance_14.geometry} material={nodes.mesh_2_instance_14.material} position={[276.9, 0, 0]} />
            <mesh geometry={nodes.mesh_2_instance_15.geometry} material={nodes.mesh_2_instance_15.material} position={[298.2, 0, 0]} />
            <mesh geometry={nodes.mesh_2_instance_16.geometry} material={nodes.mesh_2_instance_16.material} position={[319.5, 0, 0]} />
            <mesh geometry={nodes.mesh_2_instance_17.geometry} material={nodes.mesh_2_instance_17.material} position={[340.8, 0, 0]} />
            <mesh geometry={nodes.mesh_2_instance_18.geometry} material={nodes.mesh_2_instance_18.material} position={[362.1, 0, 0]} />
            <mesh geometry={nodes.mesh_2_instance_19.geometry} material={nodes.mesh_2_instance_19.material} position={[383.4, 0, 0]} />
            <mesh geometry={nodes.mesh_2_instance_20.geometry} material={nodes.mesh_2_instance_20.material} position={[404.7, 0, 0]} />
            <mesh geometry={nodes.mesh_2_instance_21.geometry} material={nodes.mesh_2_instance_21.material} position={[426, 0, 0]} />
            <mesh geometry={nodes.mesh_2_instance_22.geometry} material={nodes.mesh_2_instance_22.material} position={[447.3, 0, 0]} />
            <mesh geometry={nodes.mesh_2_instance_23.geometry} material={nodes.mesh_2_instance_23.material} position={[468.6, 0, 0]} />
          </group>
          <mesh geometry={nodes['window-front'].geometry} material={nodes['window-front'].material} position={[343.448, -46.052, -4.16]} rotation={[0, 0, 0.96]} />
          <mesh geometry={nodes['window-1ac'].geometry} material={nodes['window-1ac'].material} position={[-181.468, -51.186, -45.114]} rotation={[-2.967, 0, 0]} />
          <mesh geometry={nodes.propelle2.geometry} material={nodes.propelle2.material} position={[-181.468, -51.264, 36.191]} rotation={[-0.175, 0, 0]} />
          <mesh geometry={nodes.body_1.geometry} material={nodes.body_1.material} rotation={[-Math.PI, 0, -Math.PI]} scale={1.421} />
        </group>
        <group position={[-6.744, -28.816, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.704}>
          <group position={[79.039, -38.338, 98.883]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, 1, 1]}>
            <group position={[-22.296, 34.326, 0]}>
              <mesh geometry={nodes.Cylinder_3.geometry} material={nodes.Cylinder_3.material} position={[-65.505, 0, 0.289]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
              <mesh geometry={nodes.Cylinder_2.geometry} material={nodes.Cylinder_2.material} position={[68.276, 0, 0.289]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
              <mesh geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} position={[2.441, 0, 0]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
            </group>
            <mesh geometry={nodes.Cube_2.geometry} material={nodes.Cube_2.material} position={[-14.323, 51.158, 5.34]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
          </group>
          <group position={[79.039, -38.338, -98.883]}>
            <group position={[-22.296, 34.326, 0]}>
              <mesh geometry={nodes.Cylinder_3_1.geometry} material={nodes.Cylinder_3_1.material} position={[-65.505, 0, 0.289]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
              <mesh geometry={nodes.Cylinder_2_1.geometry} material={nodes.Cylinder_2_1.material} position={[68.276, 0, 0.289]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
              <mesh geometry={nodes.Cylinder_1.geometry} material={nodes.Cylinder_1.material} position={[2.441, 0, 0]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
            </group>
            <mesh geometry={nodes.Cube_2_1.geometry} material={nodes.Cube_2_1.material} position={[-14.323, 51.158, 5.34]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/airplane/model.glb')
